### ISSUE TITLE
Custom point sources example?

### ISSUE THREAD

**Issue by genghisken** [ofrohn/d3-celestial#19]
Thanks for this code!  It's great. You give a nice example of how to add an asterism (summer triangle).  I'd really like to superimpose a lot of point sources (supernovae).  Could you give us an example of adding custom point sources (in-line JS)?  Sorry - I'm new to d3.js, so having difficulty writing the relevant functions.

**Comment by ofrohn** [comment]
I've added a new example at https://github.com/ofrohn/d3-celestial/blob/master/demo/snr.html
with supernova remnants as point sources. Since the dso-data file already had some of those I simply filtered them. 
But if you want to provide your own data inline, put them in a json-object like this
```js
var jsonSN = {
  "type":"FeatureCollection",
  // this is an array, add as many objects as you want
  "features":[
    {"type":"Feature",
     "id":"SomeDesignator",
     "properties": {
       // Name
       "name":"Some Name",
       // magnitude or any other size criterium
       "mag": 10
     }, "geometry":{
       // the line object as an array of point coordinates
       "type":"Point",
       "coordinates": [-80.7653, 38.7837]
     }
    }  
  ]};
```
It is quite simple for point sources, since youu only need one coordinate (in [-180..180º, -90..90º] form), a name and designator, which may be the same, and a size criterium, if you want to plot your sources with different sizes, e.g. maximum magnitude.

Adding the data works the same as in the asterism example, make sure you give it a distinct class name (here "snr") with which it will be called later in the drawing function:
```js
redraw: function() {
  // Select the added objects by class name as given previously
  Celestial.container.selectAll(".snr").each(function(d) {
    // If point is visible (this doesn't work automatically for points)
    if (Celestial.clip(d.geometry.coordinates)) {
      // get point coordinates
      var pt = Celestial.mapProjection(d.geometry.coordinates);
      // object radius in pixel, could be varable depending on e.g. dimension or magnitude 
      var r = Math.pow(20 - prop.mag, 0.7); // replace 20 with dimmest magnitude in the data
   
      // draw on canvas
      // Set color
      Celestial.setStyle(pointStyle);
      Celestial.context.beginPath();
      Celestial.context.arc(pt[0], pt[1], r, 0, 2 * Math.PI);
      Celestial.context.closePath();
      Celestial.context.fill();     

      // Set text styles       
      Celestial.setTextStyle(textStyle);
      // and draw text on canvas
      Celestial.context.fillText(d.properties.name, pt[0]+r, pt[1]+r);
    }      
  }); 
}});
```
This draws the sources as circles on the canvas and the names next to them. With the Celestial.context objext you have the full range of html5-canvas funktions available, so you can draw any shape you like.

**Comment by ofrohn** [comment]
I've added and expanded the above to the readme.md

**Comment by DanielO** [comment]
I used this to overlay a map of meteor radiant intensities which you might want to crib from.
I don't have it in GitHub but you can look at the source of http://www.gsoft.com.au/~doconnor/d3-celestial/demo/radiant.html

**Comment by ofrohn** [comment]
Thanks, DanielO for the backup in case I am too incomprehesible :(

**Comment by ofrohn** [comment]
I posted an extended example on my blog here:
http://armchairastronautics.blogspot.com/2019/03/how-to-put-point-source-data-on.html
