### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by 1valdis** [ofrohn/d3-celestial#32]
Hello there,

I'm wondering if there's some sort of a roadmap or list of TODOs/"would be nice to have" stuff. So that somebody like me could use it to suggest merge requests?

**Comment by ofrohn** [comment]
Sorry for the late comment, I was terribly busy for the last few months.
I agree having a roadmap would be nice. I'll probably put one on the associated wiki, since I don't use that at all right now. This section here is always open for feature requests, and "pull requests" does what you suggest with merge requests, I think.

**Comment by ofrohn** [comment]
I went ahead and put a roadmap in the wiki at https://github.com/ofrohn/d3-celestial/wiki/Roadmap
