### ISSUE TITLE
Time and image save

### ISSUE THREAD

**Issue by mrhardass** [ofrohn/d3-celestial#39]
Hi how can i add a Button to save the image to database, instaed of right click and save, and i didnt understand how Change the years more than 10 years from the year we are

**Comment by ofrohn** [comment]
Adding a button is pretty simple, just add a link to the page, id'd "btnDowload" in the snipped below:
```js
var button = document.getElementById('btnDownload'),
    filename =  'd3-celestial.png';
button.setAttribute('download', filename);
button.addEventListener('click', function (e) {
  var canvas = document.querySelector('#celestial-map canvas'),
      dataURL = canvas.toDataURL('image/png').replace('image/png', 'image/octet-stream');
  button.href = dataURL;
});
```
Adapt the filename to your liking, and the replace is necessary to get a download instead of just the image displayed, according to stack overflow.

To change the year selection to more than 10 years you can set the config parameter 'daterange' to 
the 2-value array [startyear, endyear]
