### ISSUE TITLE
MOON size

### ISSUE THREAD

**Issue by kgoyal000** [ofrohn/d3-celestial#73]
hello @ofrohn first thanks for this awesome library , i want to increase the moon size i can't find any option can you please help.
And thanks again 🙂

**Comment by ofrohn** [comment]
Since you closed it, you probably have found the location in the code where it was hard-coded, basically to make it the same size as the sun.
However, since a hard-coded number is always worse than a configurable one, I added an override to the configuration, under planets.symbols:
``` "lun": {symbol: "\u25cf", letter:"L", fill: "#ffffff", size: 12},```
where the number for size is the (approximate) diameter of the symbol.
That also gave me the opportunity to size all the planetary disks _consistently_.
So thanks for the incentive to improve the code!

**Comment by kgoyal000** [comment]
Thanks ofrohn for your time i am new to this work and really loved your library , i found that after i changed hard coded data still i have to change something in darkluna class from 121 to new value to change it in svg also but moon's opacity decreased there can you help me with that also

**Comment by kgoyal000** [comment]
Thanks ofrohn for your time , there is an another issue with planets and moon , if we check them and then try to download svg an error came up and if we again click download svg then svg got downloaded but without white side of moon

Attaching screenshots of error as well as my code i wrote to make it work but i think the code i wrote is not fine although its working
![Screenshot from 2020-05-29 20-29-04](https://user-images.githubusercontent.com/62390711/83275478-d1a7a480-a1ec-11ea-8e27-9dbe48357866.png)
![IMG_20200529_203618](https://user-images.githubusercontent.com/62390711/83275508-dbc9a300-a1ec-11ea-8116-65611ddaeadc.jpg)

**Comment by kgoyal000** [comment]
Thanks for the fix , its really helpful 🙂

**Comment by kgoyal000** [comment]
@ofrohn there still an error coming attaching the settings which i implemented check that 
when i click on download svg an error came up in console 
then 2nd time i click download svg then it downloads the svg 
* the error is same as above comment screenshot
![Screenshot_2020-05-29-23-33-18-55](https://user-images.githubusercontent.com/62390711/83290907-13444980-a205-11ea-80be-0141ffa29835.jpg)

**Comment by ofrohn** [comment]
OK, now I can replicate the error. It seems if you disable almost everything the d3.svg.customSymbol class doesn't get defined for some reason. Not sure why, but if I pull the declaration out of the saveSVG function it doesn't produce the error under the exact same settings. So I think I'll just do that and be done with it.

**Comment by ofrohn** [comment]
Can you check?

**Comment by kgoyal000** [comment]
Thanks its all error free now really appreciate your time , sorry to bother you again but is this possible in future versions that if we increase width of canvas stars , planets all increase their sizes too , because we have to manually change the stellar size with exponential for stars  to make them look nice

**Comment by ofrohn** [comment]
In the latest version the size of planetary objects is scaled when zooming in. That'll probably do what you want

**Comment by kgoyal000** [comment]
Thanks ofrohn your work and personality is out of this world , thanks again

**Comment by kgoyal000** [comment]
Hello ofrohn , hope you are doing well
i found another issue with moon if we change symbol fill color to any other color it gets affected only on svg not on canvas

**Comment by ofrohn** [comment]
Good catch. That was a choice to use a hard-coded color for the moon symbol.
But there really isn't any good reason to ignore the configuration setting, so I fixed if now.

**Comment by kgoyal000** [comment]
Hi ofrohn sorry for disturbing again , i have a question i want to know whether i can use 🌑 this symbol for back moon or not 
when i replaced this with all moon unicode character's still that didn't worked for me , please guide me is that possible or not
Thanks

**Comment by ofrohn** [comment]
I'm not sure I understand the issue correctly: You'd like to use a Unicode Moon symbol instead of the generated crescent?
If yes, that is currently not possible because I always show the generated symbol with the settings 'symbol' and 'disk', because I like it so much. If you insist, I provide an override so that the 'symbol' setting uses the Unicode character.

**Comment by kgoyal000** [comment]
I wany moon to look like this , i thought this looks good than just white moon , but i don't know how i can achieve this
Please help me in this
![IMG_20200606_014730](https://user-images.githubusercontent.com/62390711/83919293-edd0b600-a797-11ea-90d6-d879a2ea2bf8.jpg)

**Comment by ofrohn** [comment]
So you want to display the generated crescent in front of the unicode symbol? Well, that is pretty complicated, since the size of the crescent has to match the symbol exactly. That is somewhat problematic, since there are differences between fonts, browsers and OSes how the unicode is displayed.
But if you want to do it for yourself for one specific setup, thsi code instead of the "darkluna" background circle should get you started:
```
  planets.selectAll(".dmoon")
    .data(jlun.features)
    .enter().append("text")
    .attr({dy: ".2em", dx: "-.75em", class: "darkluna"})
    .style ( "fill", "#000" )
    .attr("transform", function(d) { return point(d.geometry.coordinates); })
    .text("🌑");
```
And adapt the size of the crescent in the configuration object via the size parameter in planets -> symbols -> "lun". The dy and dx attributes in the snippet above may need some adjustment as well.

**Comment by kgoyal000** [comment]
Thanks ofrohn , i just want to improve the code and want to know that how is this thing possible , i will definitely try as you said
Thanks again
