### ISSUE TITLE
FireFox 78.0.2 (64-bit) Browser issue

### ISSUE THREAD

**Issue by Dave1680** [ofrohn/d3-celestial#88]
Hi  There,

I have been using your d3-celestial script since 29th March 2020 and have just noticed that although everything is fine in the new MS Edge, there is a slight problem in the displaying of the planet symbols when you use Firefox 78.0.2.

In MS Edge the planets appear normally, but in Firefox the planets are missing when you load the screen in at  least 50% of the time, but they pop back if you use the mouse and move the map. 

I have tried this on the un-edited "d3-celestial-master/demo/language.html" downloaded on the date above.

My question is there a fix for this without asking the user to move the map with the mouse.

Thanks,  Dave

**Comment by ofrohn** [comment]
Hi,
sorry for the late answer, I've had zero time for non-rent-paying activities in the last few weeks.
The issue had been in the code for some time, but should be fixed in the latest version.
If you modified the code and don't want to update, just put a redraw after the line where the planets get added to the path like:
```js
      container.selectAll(".planets")
         .data(pl)
         .enter().append("path")
         .attr("class", "planet");
      redraw();
```

**Comment by Dave1680** [comment]
Hi,
I added the line you suggested, it had no affect, you still have to move the map with the mouse to get the planets to appear in the latest version of FireFox (it is fine in MS Edge).
Dave.
